### ISSUE TITLE
Answers not displaying on mobile app

### ISSUE THREAD

**Issue by maccmaxitrc** [ecampbell/moodle-qtype_multichoiceset#12]
Moodle 3.9.3+ (Build: 20201211)
All-or-Nothing Multiple Choice 1.7.1 for Moodle 3.9 (2020112001)

Answers for this question type don't appear to display on the mobile app:

![image](https://user-images.githubusercontent.com/69522645/108539544-61224580-729d-11eb-9f03-ce18b21188b8.png)

They seem to display fine on desktop:

![image](https://user-images.githubusercontent.com/69522645/108539734-9890f200-729d-11eb-95d9-554cccf7b011.png)

**Comment by ecampbell** [comment]
Hi there,
Apologies for not responding sooner. I just released version 1.7.3, which addressed a bug in 1.7.1, so can you install the new version and try again?

**Comment by ecampbell** [comment]
Unfortunately this bug is present in the latest version for Moodle 3.9 and 3.10, which is 1.7.5. I will investigate further.

**Comment by roshkovan** [comment]
Hi @ecampbell
Did you fix this bug in the last plugin version 1.8.0 for moodle 3.8 and can I install 1.8.0 to moodle 3.9 ? We really need it fix)

**Comment by ecampbell** [comment]
Unfortunately this bug is not fixed. I'm not an expert on the mobile app, so although I had a look a while back, I was unable to figure out the issue. I hope to take another look over the summer.

**Comment by roshkovan** [comment]
In version 1.9.1 this bug has been fixed. Thanks!

**Comment by maccmaxitrc** [comment]
We have also confirmed that this issue is fixed. Many students will benefit from your hard work this coming semester. Thanks a bunch!
