### ISSUE TITLE
Checkbox not visible on narrow screens

### ISSUE THREAD

**Issue by t-schroeder** [ecampbell/moodle-qtype_multichoiceset#19]
When there's not enough horizontal space the checkboxes can shrink and completely disappear. For some mobile users certain answers are then not selectable. Example:

<img src="https://user-images.githubusercontent.com/24255259/120681239-76615f80-c49b-11eb-956d-0323ca756171.gif" width="600" />

This is the used question (unzip and import as Moodle XML format):
[GEMS [WZL-MQ]-Zulässige Vereinfachungen eines Netzwerks-20210603-1843.zip](https://github.com/ecampbell/moodle-qtype_multichoiceset/files/6593139/GEMS.WZL-MQ.-Zulassige.Vereinfachungen.eines.Netzwerks-20210603-1843.zip)

**Edit:**
Happens with:
* Windows Chrome
* Windows Edge
* MacOS Chrome

Doesn't happen with:
* Windows Firefox
* MacOS Firefox
* MacOS Safari

**Comment by maccmaxitrc** [comment]
This is an issue that affects all question types that allow radio buttons and checkboxes. Paste the follwing fix in the "Raw SCSS" section of your theme. (Site adminitration -> Appearance -> Themes -> Boost -> Advanced Settings -> Raw SCSS)

/*Fix for shrinking input fields*/
input[type=radio], input[type=checkbox]{
min-width:13px;
}
