### ISSUE TITLE
Display problem

### ISSUE THREAD

**Issue by rezeau** [ecampbell/moodle-qtype_multichoiceset#20]
Using latest version 1.8.0 (Build: 2021042501) (2021042501) on Moodle 3.11 (Build: 20210517).
1.- The checkboxes should be aligned with the question text. 
2.- If the numbering option is selected, the numbers (or letters) overlap with the beginning of the answer text.
![2021-07-05_15-48-01](https://user-images.githubusercontent.com/503583/124481766-f20b4080-dda8-11eb-850e-7266b73d37b9.jpg)

**Comment by rezeau** [comment]
Hi @ecampbell !
Further to an exchange on the https://moodle.org/plugins/qtype_oumultiresponse discussion yesterday, I think I found a fix for this display bug with this change in your plugin styles.css file:
.que.multichoiceset .answer div.r0,
.que.multichoiceset .answer div.r1 {
    //padding: 0.3em 0 0.3em 25px;
    //text-indent: -25px;
    display: flex;
    flex-wrap: inherit;
    text-indent: inherit;
    padding: inherit;
}
Hope that helps.
Joseph
![2021-07-07_14-48-58](https://user-images.githubusercontent.com/503583/124763075-de401580-df33-11eb-8a66-22f3013340a7.jpg)

**Comment by ecampbell** [comment]
Hi Joseph, I have released a new version 1.10.0, which contains the fix you suggest in the CSS file.

**Comment by rezeau** [comment]
Works fine, thanks!
