### ISSUE TITLE
Checkboxes not alligned, Numbering of Question overlapping with beginning of question

### ISSUE THREAD

**Issue by peter-lernyx** [ecampbell/moodle-qtype_multichoiceset#26]
![image](https://user-images.githubusercontent.com/75390480/146823242-4c06e676-1765-4711-bcf6-3bcd3a8c1ee3.png)

This was raised on Moodle plugins directory by two people. Any fix for this already? Unfortunately not usable like this...

**Comment by peter-lernyx** [comment]
Found a workaround for the overlapping numbering, just insert 3 spaces before the answer. Not great but works fine. But is should be alligned with the checkbox, otherwise students can claim it was confusing and test is void.

![image](https://user-images.githubusercontent.com/75390480/146823644-373f4ff9-65e0-4e43-9b5e-0e3ecd56c97f.png)

**Comment by ecampbell** [comment]
Can you tell me what version of Moodle you are using? This seems to be a problem in version 3.10, but not in 3.9 or 3.11.

**Comment by peter-lernyx** [comment]
![image](https://user-images.githubusercontent.com/75390480/147887718-648230ab-5b78-4540-b356-c905b851f74b.png)

**Comment by peter-lernyx** [comment]
Just upgraded to latest Moodle version (3.11.4) and latest template version (SNAP 3.11.3, dated Dec 7th 2021) purged all cashes and the problem persists:

![image](https://user-images.githubusercontent.com/75390480/147889008-3f76df38-7889-48c5-b02a-a94adaef58d6.png)

**Comment by peter-lernyx** [comment]
Switched to standard template BOOST for good measure and problem persists:
![image](https://user-images.githubusercontent.com/75390480/147889070-f8f3061b-517b-466e-88b1-a9dfbebc0da3.png)

**Comment by peter-lernyx** [comment]
![image](https://user-images.githubusercontent.com/75390480/147889110-f34934ff-5221-472e-a713-56f5e23a1486.png)

**Comment by peter-lernyx** [comment]
![image](https://user-images.githubusercontent.com/75390480/147889128-70d66c0d-7765-4917-914e-6f061234e3ec.png)

**Comment by ecampbell** [comment]
Can you tell me what version of the plugin you are using?

**Comment by peter-lernyx** [comment]
![image](https://user-images.githubusercontent.com/75390480/147889512-042dcb16-b039-4c13-8ec1-aae24e817126.png)


Just saw that there's an update available, let me quickly install that

**Comment by peter-lernyx** [comment]
Well, what do you know. After updating both the site and the plugin, it seems to be working now. 
That's excellent, thank you for pointing me to that. ;-)

![image](https://user-images.githubusercontent.com/75390480/147889588-0486cf7d-dac5-4075-bc14-30b55bbe38ea.png)

**Comment by ecampbell** [comment]
Good to hear it. Happy New Year!
