### ISSUE TITLE
checkbox are tiny using Chrome browser moodle. 3.11.5

### ISSUE THREAD

**Issue by sadawie** [ecampbell/moodle-qtype_multichoiceset#29]
testing on Chrome and Firefox. we noticed the checkbox are tiny and unusable if using Chrome.

**Comment by ecampbell** [comment]
Hi there, I can't reproduce this issue when running Chrome on Windows 10, with Moodle 3.11.5.
Can you give me more details about what platform you are running your browser on? A screenshot would help too.

**Comment by sadawie** [comment]
Here is a screenshot. I noticed it shows small check box when using longer text for options like shown in the screenshot. I did test again with short text and it shows checkbox normal but not when using longer text. 
![image](https://user-images.githubusercontent.com/29485489/164520318-18f6677f-47ae-46fe-9891-9605f5e8bbf9.png)

**Comment by sadawie** [comment]
Okay, it looks like it's related to our environment where we introduced a fix for this https://tracker.moodle.org/browse/MDL-71366 . it's all good now.
