### ISSUE TITLE
qtype_multichoiceset_options

### ISSUE THREAD

**Issue by whysea-up** [ecampbell/moodle-qtype_multichoiceset#37]
I have installed the multichoiceset it used to work fine on my previous moodle. I have a bunch of questions of that type. I have now made a fresh install of moodle, but somehow this question type isn't working. I can't see the questions,  and it asks for qtype_multichoiceset_options..

![image](https://github.com/ecampbell/moodle-qtype_multichoiceset/assets/80071766/e542c55b-8fce-4344-96b1-a061d2ac9f2c)

any idea?

**Comment by ecampbell** [comment]
Have you re-installed a new version of multichoiceset that is compatible with the new Moodle version? What Moodle version are you using now?

**Comment by whysea-up** [comment]
I have reinstalled multichoiceset, and I am using the latest moodle.

**Comment by whysea-up** [comment]
Sorry, problem solved : I have reinstalled multichoiceset on top of itself, and it solved the problem.
