### ISSUE TITLE
Checkbox vertical alignment in Moodle 3.9

### ISSUE THREAD

**Issue by JamesNGarrett** [ecampbell/moodle-qtype_multichoiceset#6]
Checkboxes labels are out of vertical alignment with their corresponding checkboxes.  Radio buttons are fine.

I tried this on Moodle 3.9 using both classic and boost theme.

As a rough workaround I added the following css:

    .multichoiceset .answer label.w-100 {margin-top: -20px;}

**Comment by absinthe-minded** [comment]
We're having the same issue

**Comment by ecampbell** [comment]
I have made a new release (v.1.6.6) to fix this problem, see https://moodle.org/plugins/pluginversion.php?id=21958. Thanks for pointing it out, and for providing the fix, James. I just added your suggestion using ems rather than pixels for the dimensions.
