### ISSUE TITLE
Moodle 3.9 - overlapping 

### ISSUE THREAD

**Issue by aspark21** [ecampbell/moodle-qtype_multichoiceset#8]
Moodle 3.9.3 
multichoiceset latest master @ 02223a11

The option a/b/c/d and the choices wording overlap. Happens both in Boost & our theme.
<img width="796" alt="Screenshot 2020-11-13 at 07 11 24" src="https://user-images.githubusercontent.com/4015496/99040197-9cb3c200-2580-11eb-9d56-2cd9aaf7164d.png">
<img width="1068" alt="Screenshot 2020-11-13 at 07 11 05" src="https://user-images.githubusercontent.com/4015496/99040205-9e7d8580-2580-11eb-9383-4cd00fe5e9d7.png">

**Comment by ecampbell** [comment]
That's odd, as I got a fix for that bug 4 months ago, see https://github.com/ecampbell/moodle-qtype_multichoiceset/blob/master/styles.css#L22
Can you check if your CSS file has the directive to fix it?

**Comment by ecampbell** [comment]
I think my original CSS fix clashed with the standard multichoice CSS, so I have now copied over the 3.9 changes from the /question/type/multichoice/styles.css file. I have now released version 1.7.0, which fixes this issue, and also now supports the new 3.9 "Show standard instructions" field too.
