### ISSUE TITLE
[feature request] Option to ignore one answer

### ISSUE THREAD

**Issue by martinalex000** [ecampbell/moodle-qtype_multichoiceset#9]
Not a bug, but a feature that would really help us in our everyday-use of this question type.

It would be great if one could not only mark possible answers as correct, but also as "don't care", that is, they should be ignored when evaluating the question.

The background behind this request is that we regularly detect that the phrasing of one particular answer was ambiguous and we would like to accept both answers. So far this is not possible and requires us to manually adjust the grading of all affected students (which may be a couple of hundred).

**Comment by ecampbell** [comment]
I think this might be difficult to implement. I suggest that if this case arises, you set the mark for this question to 0, and then everyones answer is just ignored.
